GenericCamera/v1/_labels.yaml

Adds placeholder configuration for GenericCamera CSC.

DM-20121 Make GenericCamera configurable

---

Watcher/README.rst
Watcher/v1/_labels.yaml

DM-20148: Add the Watcher

---

Scheduler/at_20210909_target_list.yaml
Scheduler/v1/at_20210909.yaml

* Add Scheduler configuration and target list for testing.
* Use mode: ADVANCE in Scheduler config
* Add target list for survey around ra=22 and dec=-55.

In Scheduler configuration:

---

Scheduler/feature_scheduler/auxtel/2022/06/fbs_config_spec_survey.py
Scheduler/v4/auxtel_fbs_spec_202206A_blind_offset.yaml
Scheduler/v4/auxtel_fbs_spec_202206A_hot_blind_offset.yaml

* Update cold start configuration with a startup database.
* Remove spole and special spectroscopic config for spectroscopic survey.
* Add configuration with blind offset on spectroscopic survey.

In Scheduler:

---

Scheduler/feature_scheduler/auxtel/fbs_config_spec_survey.py
Scheduler/feature_scheduler/auxtel/fbs_config_spec_survey_photometric.py

Fix typo in spectroscopic target name

---

Watcher/v4/_summit.yaml
Watcher/v5/_base.yaml
Watcher/v5/_summit.yaml
Watcher/v5/_tucson.yaml

Also move escalation from v4 to v5

DM-38875: remove WeatherStation rules and add missing ESS instances

---

Watcher/v5/_summit.yaml

Add missing glob chars to the specified alarms.

DM-38887: Watcher summit config: fix escalation

---

FiberSpectrograph/v4/_init.yaml
FiberSpectrograph/v4/_summit.yaml
FiberSpectrograph/v4/_tucson.yaml

Added "location" to v4 of config files for fiber spectrograph based on changes to ts_fiberspectrograph as part of tickets/[DM-37856](https://jira.lsstcorp.org/browse/DM-37856)

added location to config file

---

Scheduler/feature_scheduler/auxtel/fbs_config_image_photocal_survey.py
Scheduler/feature_scheduler/auxtel/fbs_config_spec_survey.py
Scheduler/observing_blocks_auxtel/auxtel-drp-imaging.json
Scheduler/observing_blocks_auxtel/auxtel-photocalib-imaging.json
Scheduler/observing_blocks_auxtel/ops-cwfs.json
Scheduler/observing_blocks_auxtel/survey-spec-bright-with-rotation.json
Scheduler/observing_blocks_auxtel/survey-spec-pole-with-rotation.json
Scheduler/observing_blocks_auxtel/survey-spec-with-rotation.json

Final simulations for both surveys below.

Update AuxTel scheduler configurations and blocks for 2023-05B run.

---

DIMM/v3/_summit.yaml

updated DIMM config for new IP addresses.

BS updated DIMM IP addresses

---

Watcher/v5/_summit.yaml

* Fix GenericCamera setup for Heartbeat and Enabled alarms.
* Increase escalatino time for Heartbeat and Enabled alarms to 10 minutes.

Watcher: Update summit configuration.

---

Scheduler/observing_blocks_maintel/BLOCK-233.json

Initial commit for BLOCK-233

---

ESS/v7/_init.yaml

For the laser, the humidity sensor and temperature scanner will be connected to a RPi. For the CBP, the temperature scanner will be connected to a Moxa device over RS-232. Some work still needs to be done to make that possible.

added Laser and CBP devices for MT Dome

---

Electrometer/v6/_summit.yaml
Electrometer/v6/_tucson.yaml

Added electrometers to `_summit.yaml` for when they are eventually installed. Also added the appropriate config info for `_tucson.yaml`. This has just been sitting on a stagnant branch.

Electrometer updates for summit

---

Scheduler/feature_scheduler/auxtel/fbs_config_image_photocal_survey.py
Scheduler/observing_blocks_auxtel/BLOCK-273.json

Takes spectroscopy of a planetary nebula: https://rubinobs.atlassian.net/browse/BLOCK-273

Add ATScheduler Block 273

---

Scheduler/feature_scheduler/maintel/fbs_config_sit_survey_block_t189.py
Scheduler/observing_blocks_ocs/BLOCK-T189.json
Scheduler/v7/maintel_fbs_sit_block_t189.yaml

Adding BLOCK-T189: all-day scheduler configuration for LSSTCam OpSim with filter changes and shutter operation. Configured to use any available glass filters. To be used in LSSTCam EO test Step 9.

BLOCK-T189

---

Scheduler/feature_scheduler/auxtel/fbs_config_image_photocal_survey.py
Scheduler/feature_scheduler/auxtel/fbs_spec_flex_survey.py
Scheduler/feature_scheduler/auxtel/feb_2025_fbs_spec_survey.py
Scheduler/feature_scheduler/auxtel/jan_2025_fbs_spec_survey.py
Scheduler/feature_scheduler/auxtel/oct_2024_fbs_config_image_photocal_survey.py
Scheduler/v7/auxtel_fbs_spec_flex_survey.yaml

This works with updates in ts_fbs_utils to create more flexible auxtel configurations for spectroscopy + imaging surveys.

OPSIM-1217: Add more flexible auxtel spectroscopy configuration

---

ESS/v7/_init.yaml

I looked around but was unable to find a DNS name for this machine.

Fix some errors in the RINGSS configuration.

---

Scheduler/feature_scheduler/maintel/ddf_sv.dat
Scheduler/feature_scheduler/maintel/fbs_config_sv_survey.py
Scheduler/v7/fbs_config_sv_survey.yaml

Add yaml file with 20% TMA motion plus configuration for the FBS 
(this should be modified to use a different sqlite file, but I don't know what that would be)
Add SV configuration file.

SP-2347: Add SV survey configurations

---

EAS/v6/disable_m1m3ts.yaml
EAS/v6/track_with_dome_closed.yaml

Forgot to copy these files from the v5 directory to v6.

Add extra yaml files for EAS v6
